# Funciones y librerias en python

## Definición de una función

In [8]:
## que es un función?
def promedio(numero1,numero2,numero3):
    resultado = (numero1+numero2+numero3)/3
    return resultado

resultado_funcion = promedio(10,15,80)
resultado_funcion2 = promedio(1,2,3)
print(f"el promedio de los numeros es: {resultado_funcion}")
print(f"el promedio de los numeros es: {resultado_funcion2}")

el promedio de los numeros es: 35.0
el promedio de los numeros es: 2.0


In [3]:
def mi_formula_magica(entrada1,entrada2):
    resultado = entrada1**2-entrada2**(0.5)
    return resultado

In [5]:
mi_formula_magica(876,124)

767364.8644712743

## Librerias famosas
Numpy - Scipy

In [18]:
# importar libreria
import numpy as np

# Crear un array NumPy
mi_vector = np.array([1,-2,3])
print(mi_vector)
# Realizar operaciones en el array
print(mi_vector+np.array([4,5,6]))

np.append(mi_vector,11)

[ 1 -2  3]
[5 3 9]


array([ 1, -2,  3, 11])

Este ejemplo muestra cómo SciPy se puede utilizar para resolver un sistema de ecuaciones lineales.
\begin{align}
AX = B
\end{align}

\begin{align}
        A = \begin{pmatrix}
        a_{11} & a_{12} \\
        a_{21} & a_{22}
        \end{pmatrix}
    \end{align}

\begin{align}
        B = \begin{pmatrix}
        b_{1}  \\
        b_{2}
        \end{pmatrix}
    \end{align}

\begin{align}
        X = \begin{pmatrix}
        x  \\
        y
        \end{pmatrix}
    \end{align}

\begin{align}
\left. a_{11}x + a_{12}y = b_1 \atop a_{21}x + a_{22}y = b_2 \right\}
\end{align}

In [20]:
import numpy as np
from scipy.linalg import solve

# Coeficientes de las ecuaciones
A = np.array([[1, 1], [1, -1]]) #2x2
b = np.array([20, 10])

# Resolver el sistema de ecuaciones
x = solve(A, b)

print("Solución del sistema de ecuaciones:")
print("x =", x[0])
print("y =", x[1])


Solución del sistema de ecuaciones:
x = 15.0
y = 5.0
